name: "refresh"

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: install depend
        if: success()
        run: |
          sudo apt update 2>>/dev/null 1>>/dev/null
          sudo apt install apt-utils gawk sed bzip2 xz-utils zstd -y

      - name: Refresh Packages
        if: success()
        run: |
          rm -rf ./Packages*
          sudo apt-ftparchive packages ./debs | awk -v RS="" -v ORS="\0" '1' | sort -z | awk -v RS="\0" -v ORS="\n\n" '1' | sed '/./,$!d' > Packages
          bzip2 -v -k -9 Packages
          xz -v -k -9 --extreme Packages
          zstd --ultra -22 -k Packages -o Packages.zst

      - name: save change if local change
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --staged --exit-code 1>>/dev/null; then
            git commit -m 'Refresh Packages'
            git push
          fi

  remove_all_old_actions:
    uses: invalidunit/action/.github/workflows/remove_all_actions.yml@main
